### ISSUE TITLE
strange error message

### ISSUE THREAD

**Issue by lkwg82** [idealo/logback-redis#14]
Exception while retrying to append the event '[ERROR] Exception while retrying to append the event 'null' with a re-initialized Jedis client. The event is lost.' with a re-initialized Jedis client. The event is lost.

```
redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:51)
    at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:209)
    at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:17)
    at de.idealo.logback.appender.RedisBatchAppender.initJedisClient(RedisBatchAppender.java:220)
    at de.idealo.logback.appender.RedisBatchAppender.append(RedisBatchAppender.java:122)
    at de.idealo.logback.appender.RedisBatchAppender.append(RedisBatchAppender.java:34)
    at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
    at net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler.onEvent(DelegatingAsyncDisruptorAppender.java:53)
    at net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler.onEvent(DelegatingAsyncDisruptorAppender.java:49)
    at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:320)
    at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:308)
    at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Unable to validate object
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
    at redis.clients.util.Pool.getResource(Pool.java:49)
    ... 19 common frames omitted
```

The event is not lost and later reported, but logged as error.

This error happend at the time we had internal DNS problems.

**Comment by vsdev1** [comment]
Are you sure that the event is not lost? Do you have a setup where this behavior can be reproduced (e.g. via an integration test with embedded redis server)?

**Comment by lkwg82** [comment]
as of this seems obscure not reproduceable

**Comment by brmeloleite01** [comment]
Hey I had the same issue! But the event is not null. I couldn't solve it  too.
This problem have already happened twice at this month and that exception have consumed whole space from HD.

Would you mind reopen this issue??

**Comment by lkwg82** [comment]
Is this library still maintained?

**Comment by mgerlach** [comment]
I guess it should be... However the redis setup has been almost completely (if not entirely) replaced by alternative solutions in idealo, so the maintainers, who are all still with the company, won't be able to invest a lot of time in their working hours... 

@brmeloleite01 , would you be able to debug/analyze?

**Comment by lkwg82** [comment]
I have not seen the issue for years, so maybe updating everything around could solve it.

**Comment by lkwg82** [comment]
@brmeloleite01 if you can reproduce it with a test case it can probably fixed.

Or you can offer a fix.

**Comment by mgerlach** [comment]
I have to correct my comment about the maintainers. I was referring to developers with admin/maintain/write access to the repo. There are 3 and they are all with idealo.

However, of the devs listed in pom.xml, only I am still at idealo. @doernbrackandre, are you still using this lib? 

@lkwg82, you may be right, adding a proper dependabot config to bump some dependencies would not be that much effort.

But a test reproducing the bug would be best.

**Comment by brmeloleite01** [comment]
@mgerlach Unfortunately I cannot reproduce it. I have a cluster and 1 out of 8 nodes had this exception. This happened only twice at this month... So I don't know what I can do.

The application was written in spring boot (groovy)

The Redis service (Elasticache) had no problems at the time of this error.
